// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: homepanel

#ifndef _HOMEPANEL_UI_H
#define _HOMEPANEL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_ScreenConnect.h"
#include "ui_ScreenOTA.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_button_latst_png);    // assets/button_latst.png
LV_IMG_DECLARE(ui_img_button_back_png);    // assets/button_back.png
LV_IMG_DECLARE(ui_img_button_new_png);    // assets/button_new.png
LV_IMG_DECLARE(ui_img_thermometer3_png);    // assets/thermometer3.png

// FONTS
LV_FONT_DECLARE(ui_font_dsdigib100);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
