// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: homepanel

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void activity_event_handler(lv_event_t * e);
void buttonLight_event_handler(lv_event_t * e);
void buttonSelectLight_event_handler(lv_event_t * e);
void buttonLatest_event_handler(lv_event_t * e);
void buttonBack_event_handler(lv_event_t * e);
void buttonNew_event_handler(lv_event_t * e);
void buttonTempLocation_event_handler(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
