// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: homepanel

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_labelConnectionStatus = NULL;
lv_obj_t * ui_ButtonLatest = NULL;
lv_obj_t * ui_ButtonBack = NULL;
lv_obj_t * ui_ButtonNew = NULL;
lv_obj_t * ui_labelPowerValue = NULL;
lv_obj_t * ui_labelEnergyValue = NULL;
lv_obj_t * ui_powerLabel = NULL;
lv_obj_t * ui_energyLabel = NULL;
lv_obj_t * ui_labelTimeDate = NULL;
// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        activity_event_handler(e);
    }
}

void ui_event_ButtonLatest(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        activity_event_handler(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        buttonLatest_event_handler(e);
    }
}

void ui_event_ButtonBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        activity_event_handler(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        buttonBack_event_handler(e);
    }
}

void ui_event_ButtonNew(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        activity_event_handler(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        buttonNew_event_handler(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelConnectionStatus = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelConnectionStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelConnectionStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelConnectionStatus, -115);
    lv_obj_set_y(ui_labelConnectionStatus, -138);
    lv_obj_set_align(ui_labelConnectionStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelConnectionStatus, "Status");
    lv_obj_set_style_text_font(ui_labelConnectionStatus, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonLatest = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonLatest, 128);
    lv_obj_set_height(ui_ButtonLatest, 143);
    lv_obj_set_x(ui_ButtonLatest, -48);
    lv_obj_set_y(ui_ButtonLatest, 117);
    lv_obj_set_align(ui_ButtonLatest, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonLatest, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonLatest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonLatest, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonLatest, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonLatest, &ui_img_button_latst_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ButtonLatest, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_ButtonLatest, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonBack = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonBack, 138);
    lv_obj_set_height(ui_ButtonBack, 143);
    lv_obj_set_x(ui_ButtonBack, -166);
    lv_obj_set_y(ui_ButtonBack, 116);
    lv_obj_set_align(ui_ButtonBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonBack, &ui_img_button_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ButtonBack, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_ButtonBack, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonNew = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonNew, 128);
    lv_obj_set_height(ui_ButtonNew, 143);
    lv_obj_set_x(ui_ButtonNew, 68);
    lv_obj_set_y(ui_ButtonNew, 118);
    lv_obj_set_align(ui_ButtonNew, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonNew, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonNew, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonNew, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonNew, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonNew, &ui_img_button_new_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ButtonNew, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_ButtonNew, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPowerValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelPowerValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPowerValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPowerValue, 93);
    lv_obj_set_y(ui_labelPowerValue, -67);
    lv_obj_set_align(ui_labelPowerValue, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_labelPowerValue, "--");
    lv_obj_set_style_text_color(ui_labelPowerValue, lv_color_hex(0xE9B804), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPowerValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPowerValue, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelEnergyValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelEnergyValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelEnergyValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelEnergyValue, 94);
    lv_obj_set_y(ui_labelEnergyValue, -16);
    lv_obj_set_align(ui_labelEnergyValue, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_labelEnergyValue, "--");
    lv_obj_set_style_text_color(ui_labelEnergyValue, lv_color_hex(0xE9B804), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelEnergyValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelEnergyValue, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_powerLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_powerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_powerLabel, -191);
    lv_obj_set_y(ui_powerLabel, -67);
    lv_obj_set_align(ui_powerLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_powerLabel, "Power:");
    lv_obj_set_style_text_color(ui_powerLabel, lv_color_hex(0xB2B2B2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_powerLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_powerLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_energyLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_energyLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_energyLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_energyLabel, -194);
    lv_obj_set_y(ui_energyLabel, -14);
    lv_obj_set_align(ui_energyLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_energyLabel, "Energy:");
    lv_obj_set_style_text_color(ui_energyLabel, lv_color_hex(0xB2B2B2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_energyLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_energyLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTimeDate = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelTimeDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTimeDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTimeDate, 269);
    lv_obj_set_y(ui_labelTimeDate, -138);
    lv_obj_set_align(ui_labelTimeDate, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_labelTimeDate, "18 Jan 2026, 14:31:10");
    lv_obj_set_style_text_color(ui_labelTimeDate, lv_color_hex(0xB2B2B2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelTimeDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelTimeDate, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonLatest, ui_event_ButtonLatest, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonBack, ui_event_ButtonBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonNew, ui_event_ButtonNew, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_labelConnectionStatus = NULL;
    ui_ButtonLatest = NULL;
    ui_ButtonBack = NULL;
    ui_ButtonNew = NULL;
    ui_labelPowerValue = NULL;
    ui_labelEnergyValue = NULL;
    ui_powerLabel = NULL;
    ui_energyLabel = NULL;
    ui_labelTimeDate = NULL;

}
