// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: homepanel

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_labelConnectionStatus;
extern void ui_event_ButtonLight(lv_event_t * e);
extern lv_obj_t * ui_ButtonLight;
extern lv_obj_t * ui_lightLabel;
extern void ui_event_ButtonSelectLight(lv_event_t * e);
extern lv_obj_t * ui_ButtonSelectLight;
extern lv_obj_t * ui_selectButtonLabel;
extern lv_obj_t * ui_cameraPanel;
extern void ui_event_ButtonLatest(lv_event_t * e);
extern lv_obj_t * ui_ButtonLatest;
extern void ui_event_ButtonBack(lv_event_t * e);
extern lv_obj_t * ui_ButtonBack;
extern void ui_event_ButtonNew(lv_event_t * e);
extern lv_obj_t * ui_ButtonNew;
extern lv_obj_t * ui_labelTimeDate;
extern lv_obj_t * ui_labelTime;
extern lv_obj_t * ui_electricContainer;
extern lv_obj_t * ui_powerLabel;
extern lv_obj_t * ui_labelPowerValue;
extern lv_obj_t * ui_energyLabel;
extern lv_obj_t * ui_labelEnergyValue;
extern lv_obj_t * ui_tempContainer;
extern lv_obj_t * ui_tempPanel;
extern lv_obj_t * ui_thermometer;
extern void ui_event_ButtonTempLoc(lv_event_t * e);
extern lv_obj_t * ui_ButtonTempLoc;
extern lv_obj_t * ui_tempLocLabel;
extern lv_obj_t * ui_tempTimeLabel;
extern lv_obj_t * ui_labelOutsideTemp;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

