// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: homepanel

#include "ui.h"

lv_obj_t * ui_ScreenConnect = NULL;
lv_obj_t * ui_labelConnectStatus = NULL;
// event funtions
void ui_event_ScreenConnect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        activity_event_handler(e);
    }
}

// build funtions

void ui_ScreenConnect_screen_init(void)
{
    ui_ScreenConnect = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenConnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenConnect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenConnect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelConnectStatus = lv_label_create(ui_ScreenConnect);
    lv_obj_set_width(ui_labelConnectStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelConnectStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelConnectStatus, 5);
    lv_obj_set_y(ui_labelConnectStatus, -15);
    lv_obj_set_align(ui_labelConnectStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelConnectStatus, "Connection");
    lv_obj_set_style_text_color(ui_labelConnectStatus, lv_color_hex(0xE9B804), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelConnectStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelConnectStatus, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenConnect, ui_event_ScreenConnect, LV_EVENT_ALL, NULL);

}

void ui_ScreenConnect_screen_destroy(void)
{
    if(ui_ScreenConnect) lv_obj_del(ui_ScreenConnect);

    // NULL screen variables
    ui_ScreenConnect = NULL;
    ui_labelConnectStatus = NULL;

}
