// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: homepanel

#ifndef UI_SCREENCONNECT_H
#define UI_SCREENCONNECT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenConnect
extern void ui_ScreenConnect_screen_init(void);
extern void ui_ScreenConnect_screen_destroy(void);
extern void ui_event_ScreenConnect(lv_event_t * e);
extern lv_obj_t * ui_ScreenConnect;
extern lv_obj_t * ui_labelConnectStatus;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

