// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: homepanel

#ifndef UI_SCREENOTA_H
#define UI_SCREENOTA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenOTA
extern void ui_ScreenOTA_screen_init(void);
extern void ui_ScreenOTA_screen_destroy(void);
extern lv_obj_t * ui_ScreenOTA;
extern lv_obj_t * ui_labelOTAStatus;
extern lv_obj_t * ui_labelOTAProgress;
extern lv_obj_t * ui_labelOTAWarning;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

