// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: homepanel

#include "ui.h"

lv_obj_t * ui_ScreenOTA = NULL;
lv_obj_t * ui_labelOTAStatus = NULL;
lv_obj_t * ui_labelOTAProgress = NULL;
lv_obj_t * ui_labelOTAWarning = NULL;
// event funtions

// build funtions

void ui_ScreenOTA_screen_init(void)
{
    ui_ScreenOTA = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenOTA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenOTA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenOTA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelOTAStatus = lv_label_create(ui_ScreenOTA);
    lv_obj_set_width(ui_labelOTAStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelOTAStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelOTAStatus, -8);
    lv_obj_set_y(ui_labelOTAStatus, -66);
    lv_obj_set_align(ui_labelOTAStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelOTAStatus, "Updating firmware");
    lv_obj_set_style_text_color(ui_labelOTAStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelOTAStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelOTAStatus, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelOTAProgress = lv_label_create(ui_ScreenOTA);
    lv_obj_set_width(ui_labelOTAProgress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelOTAProgress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelOTAProgress, -8);
    lv_obj_set_y(ui_labelOTAProgress, -11);
    lv_obj_set_align(ui_labelOTAProgress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelOTAProgress, "%");
    lv_obj_set_style_text_color(ui_labelOTAProgress, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelOTAProgress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelOTAProgress, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelOTAWarning = lv_label_create(ui_ScreenOTA);
    lv_obj_set_width(ui_labelOTAWarning, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelOTAWarning, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelOTAWarning, -11);
    lv_obj_set_y(ui_labelOTAWarning, 54);
    lv_obj_set_align(ui_labelOTAWarning, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelOTAWarning, "Do not power off");
    lv_obj_set_style_text_color(ui_labelOTAWarning, lv_color_hex(0xDA073A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelOTAWarning, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelOTAWarning, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ScreenOTA_screen_destroy(void)
{
    if(ui_ScreenOTA) lv_obj_del(ui_ScreenOTA);

    // NULL screen variables
    ui_ScreenOTA = NULL;
    ui_labelOTAStatus = NULL;
    ui_labelOTAProgress = NULL;
    ui_labelOTAWarning = NULL;

}
