// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: homepanel

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_screen2Text = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_imgScreen2Background = NULL;
// event funtions
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        activity_event_handler(e);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        activity_event_handler(e);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x395D4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screen2Text = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_screen2Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_screen2Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_screen2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_screen2Text, "Getting image");
    lv_obj_set_style_text_align(ui_screen2Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_screen2Text, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button2, 448);
    lv_obj_set_height(ui_Button2, 368);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgScreen2Background = lv_img_create(ui_Screen2);
    lv_obj_set_width(ui_imgScreen2Background, lv_pct(100));
    lv_obj_set_height(ui_imgScreen2Background, lv_pct(100));
    lv_obj_set_align(ui_imgScreen2Background, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgScreen2Background, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgScreen2Background, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_screen2Text = NULL;
    ui_Button2 = NULL;
    ui_imgScreen2Background = NULL;

}
