// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: homepanel

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_labelConnectionStatus = NULL;
lv_obj_t * ui_ButtonLatest = NULL;
lv_obj_t * ui_ButtonBack = NULL;
lv_obj_t * ui_ButtonNew = NULL;
lv_obj_t * ui_labelTimeDate = NULL;
lv_obj_t * ui_labelTime = NULL;
lv_obj_t * ui_electricContainer = NULL;
lv_obj_t * ui_powerLabel = NULL;
lv_obj_t * ui_labelPowerValue = NULL;
lv_obj_t * ui_energyLabel = NULL;
lv_obj_t * ui_labelEnergyValue = NULL;
lv_obj_t * ui_tempContainer = NULL;
lv_obj_t * ui_thermometer = NULL;
lv_obj_t * ui_ButtonTempLoc = NULL;
lv_obj_t * ui_tempLocLabel = NULL;
lv_obj_t * ui_tempTimeLabel = NULL;
lv_obj_t * ui_labelOutsideTemp = NULL;
// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        activity_event_handler(e);
    }
}

void ui_event_ButtonLatest(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        activity_event_handler(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        buttonLatest_event_handler(e);
    }
}

void ui_event_ButtonBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        activity_event_handler(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        buttonBack_event_handler(e);
    }
}

void ui_event_ButtonNew(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        activity_event_handler(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        buttonNew_event_handler(e);
    }
}

void ui_event_ButtonTempLoc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        activity_event_handler(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        buttonTempLocation_event_handler(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelConnectionStatus = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelConnectionStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelConnectionStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelConnectionStatus, 10);
    lv_obj_set_y(ui_labelConnectionStatus, -138);
    lv_obj_set_align(ui_labelConnectionStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelConnectionStatus, "Status");
    lv_obj_set_style_text_font(ui_labelConnectionStatus, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonLatest = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonLatest, 128);
    lv_obj_set_height(ui_ButtonLatest, 143);
    lv_obj_set_x(ui_ButtonLatest, -88);
    lv_obj_set_y(ui_ButtonLatest, 144);
    lv_obj_set_align(ui_ButtonLatest, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonLatest, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonLatest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonLatest, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonLatest, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonLatest, &ui_img_button_latst_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ButtonLatest, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_ButtonLatest, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonBack = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonBack, 138);
    lv_obj_set_height(ui_ButtonBack, 143);
    lv_obj_set_x(ui_ButtonBack, -168);
    lv_obj_set_y(ui_ButtonBack, 143);
    lv_obj_set_align(ui_ButtonBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonBack, &ui_img_button_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ButtonBack, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_ButtonBack, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonNew = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonNew, 128);
    lv_obj_set_height(ui_ButtonNew, 143);
    lv_obj_set_x(ui_ButtonNew, -6);
    lv_obj_set_y(ui_ButtonNew, 144);
    lv_obj_set_align(ui_ButtonNew, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonNew, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonNew, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonNew, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonNew, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonNew, &ui_img_button_new_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ButtonNew, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_ButtonNew, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTimeDate = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelTimeDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTimeDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTimeDate, 8);
    lv_obj_set_y(ui_labelTimeDate, -138);
    lv_obj_set_align(ui_labelTimeDate, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_labelTimeDate, "18 Jan 2026");
    lv_obj_set_style_text_color(ui_labelTimeDate, lv_color_hex(0xB2B2B2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelTimeDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelTimeDate, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTime = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTime, 15);
    lv_obj_set_y(ui_labelTime, -76);
    lv_obj_set_align(ui_labelTime, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_labelTime, "--:--:--");
    lv_obj_set_style_text_color(ui_labelTime, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelTime, &ui_font_dsdigib100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_electricContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_electricContainer);
    lv_obj_set_width(ui_electricContainer, 354);
    lv_obj_set_height(ui_electricContainer, 129);
    lv_obj_set_x(ui_electricContainer, -128);
    lv_obj_set_y(ui_electricContainer, 52);
    lv_obj_set_align(ui_electricContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_electricContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_powerLabel = lv_label_create(ui_electricContainer);
    lv_obj_set_width(ui_powerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_powerLabel, -59);
    lv_obj_set_y(ui_powerLabel, -46);
    lv_obj_set_align(ui_powerLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_powerLabel, "Power:");
    lv_obj_set_style_text_color(ui_powerLabel, lv_color_hex(0xB2B2B2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_powerLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_powerLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPowerValue = lv_label_create(ui_electricContainer);
    lv_obj_set_width(ui_labelPowerValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPowerValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPowerValue, 154);
    lv_obj_set_y(ui_labelPowerValue, -48);
    lv_obj_set_align(ui_labelPowerValue, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_labelPowerValue, "--");
    lv_obj_set_style_text_color(ui_labelPowerValue, lv_color_hex(0xE9B804), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPowerValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPowerValue, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_energyLabel = lv_label_create(ui_electricContainer);
    lv_obj_set_width(ui_energyLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_energyLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_energyLabel, -64);
    lv_obj_set_y(ui_energyLabel, -7);
    lv_obj_set_align(ui_energyLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_energyLabel, "Energy:");
    lv_obj_set_style_text_color(ui_energyLabel, lv_color_hex(0xB2B2B2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_energyLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_energyLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelEnergyValue = lv_label_create(ui_electricContainer);
    lv_obj_set_width(ui_labelEnergyValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelEnergyValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelEnergyValue, 154);
    lv_obj_set_y(ui_labelEnergyValue, -7);
    lv_obj_set_align(ui_labelEnergyValue, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_labelEnergyValue, "--");
    lv_obj_set_style_text_color(ui_labelEnergyValue, lv_color_hex(0xE9B804), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelEnergyValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelEnergyValue, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_tempContainer);
    lv_obj_set_width(ui_tempContainer, 134);
    lv_obj_set_height(ui_tempContainer, 137);
    lv_obj_set_x(ui_tempContainer, 188);
    lv_obj_set_y(ui_tempContainer, -99);
    lv_obj_set_align(ui_tempContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tempContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_thermometer = lv_img_create(ui_tempContainer);
    lv_img_set_src(ui_thermometer, &ui_img_thermometer3_png);
    lv_obj_set_width(ui_thermometer, LV_SIZE_CONTENT);   /// 55
    lv_obj_set_height(ui_thermometer, LV_SIZE_CONTENT);    /// 172
    lv_obj_set_x(ui_thermometer, 39);
    lv_obj_set_y(ui_thermometer, -31);
    lv_obj_set_align(ui_thermometer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_thermometer, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_thermometer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_thermometer, 80);

    ui_ButtonTempLoc = lv_btn_create(ui_tempContainer);
    lv_obj_set_width(ui_ButtonTempLoc, 100);
    lv_obj_set_height(ui_ButtonTempLoc, 36);
    lv_obj_set_x(ui_ButtonTempLoc, -1);
    lv_obj_set_y(ui_ButtonTempLoc, 17);
    lv_obj_set_align(ui_ButtonTempLoc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTempLoc, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonTempLoc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tempLocLabel = lv_label_create(ui_tempContainer);
    lv_obj_set_width(ui_tempLocLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempLocLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempLocLabel, -1);
    lv_obj_set_y(ui_tempLocLabel, 18);
    lv_obj_set_align(ui_tempLocLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLocLabel, "Outside");
    lv_obj_set_style_text_font(ui_tempLocLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempTimeLabel = lv_label_create(ui_tempContainer);
    lv_obj_set_width(ui_tempTimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempTimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempTimeLabel, -5);
    lv_obj_set_y(ui_tempTimeLabel, -15);
    lv_obj_set_align(ui_tempTimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempTimeLabel, "14:52");
    lv_obj_set_style_text_font(ui_tempTimeLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelOutsideTemp = lv_label_create(ui_tempContainer);
    lv_obj_set_width(ui_labelOutsideTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelOutsideTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelOutsideTemp, 9);
    lv_obj_set_y(ui_labelOutsideTemp, -43);
    lv_obj_set_align(ui_labelOutsideTemp, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_labelOutsideTemp, "-28.5 C");
    lv_obj_set_style_text_color(ui_labelOutsideTemp, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelOutsideTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelOutsideTemp, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonLatest, ui_event_ButtonLatest, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonBack, ui_event_ButtonBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonNew, ui_event_ButtonNew, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonTempLoc, ui_event_ButtonTempLoc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_labelConnectionStatus = NULL;
    ui_ButtonLatest = NULL;
    ui_ButtonBack = NULL;
    ui_ButtonNew = NULL;
    ui_labelTimeDate = NULL;
    ui_labelTime = NULL;
    ui_electricContainer = NULL;
    ui_powerLabel = NULL;
    ui_labelPowerValue = NULL;
    ui_energyLabel = NULL;
    ui_labelEnergyValue = NULL;
    ui_tempContainer = NULL;
    ui_thermometer = NULL;
    ui_ButtonTempLoc = NULL;
    ui_tempLocLabel = NULL;
    ui_tempTimeLabel = NULL;
    ui_labelOutsideTemp = NULL;

}
