// Custom UI extensions for Home Panel
// This file is NOT generated by SquareLine Studio and won't be overwritten

#ifndef UI_CUSTOM_H
#define UI_CUSTOM_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

// Track previous screen for navigation (used by image_fetcher)
extern lv_obj_t * ui_previous_screen;

// Screen2 image display state management
void ui_Screen2_setImageDisplayed(bool displayed);
bool ui_Screen2_getImageDisplayed(void);

// Activity event handler - called by SquareLine generated code on user interactions
void activity_event_handler(lv_event_t * e);

#ifdef __cplusplus
}
#endif

#endif // UI_CUSTOM_H
