// Custom UI extensions for Home Panel
// This file is NOT generated by SquareLine Studio and won't be overwritten

#include "ui_custom.h"
#include "screen/screen_power.h"
#include <stdbool.h>

// Flag to track if image has been displayed on Screen2
// Used to prevent accidental back navigation while image is still loading
static bool screen2_imageDisplayed = false;

// Track previous screen for navigation (used by image_fetcher)
lv_obj_t * ui_previous_screen = NULL;

void ui_Screen2_setImageDisplayed(bool displayed) {
    screen2_imageDisplayed = displayed;
}

bool ui_Screen2_getImageDisplayed(void) {
    return screen2_imageDisplayed;
}

// Activity event handler - called by SquareLine generated code on user interactions
// Wakes screen from dim state and resets the inactivity timer
void activity_event_handler(lv_event_t * e) {
    screenPowerActivity();  // Wake screen and reset timer
    (void)e;  // Suppress unused parameter warning
}
